# Generated by Django 2.1.7 on 2019-10-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iletisim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iletisimmodel',
            name='resim',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
